### ISSUE TITLE
Multiple deserialization to same instance

### ISSUE THREAD

**Issue by ihcaesar** [d-led/picojson_serializer#13]
When deserializing with picojson::convert::from_string(jsonstring, object) multiple times to the same object, vectors inside the object will grow.

Suggestion: Initalize object with it's default constructor
```
        template < typename T>
        std::string from_string(std::string const& json, T& t) {
            **t = T();**
            picojson::value v;
            std::string err;
            picojson::parse(v, json.begin(), json.end(), &err);
            if (err.empty())
                from_value(v, t);
            return err;
        }

```

**Comment by d-led** [comment]
I need to think about it. The original design goal was similar to a [tolerant reader](http://martinfowler.com/bliki/TolerantReader.html), meaning, if you need to set defaults that might be missing in JSON, you could do so before the deserialization. 

Other question arises: if `T` does not have a default constructor?

**Comment by ihcaesar** [comment]
Ok - I understand.

The idea of calling the default constructor of T was copied from some lines below: 
`            template<typename T>
            T from_value(picojson::value const& v) {
                T t = T();
...
 `

Maybe another suggestion, if initialising is too much for a tolerant reader:
Change the from_value method of the std::vector serializer to clear the vector if the array is present in the JSON string:

```
            static void from_value(value const& ov, vector_type& v) {
                if ( !ov.is<picojson::array>() )
                    return;
**v.clear();**
				picojson::array const& a = ov.get<picojson::array>();
				std::transform(
					a.begin(),
					a.end(),
					std::back_inserter(v),
					operators::from_value<T>);
            }

```

**Comment by d-led** [comment]
thanks for your suggestion. Semantically, it's the same change, but will introduce an inconsistency: scalar fields will not get cleared, why vector contents will do. Another suggestion: what about adding one overload with another name, containing the default initialization, i.e. `initialize_from_string`.

A quick question: do you use this library in some kind of productive code? This library https://github.com/USCiLab/cereal seems to be quite superior to mine, but is c++11.

**Comment by ihcaesar** [comment]
I thought my change cleared vector contents only if the data array is present in the JSON data - otherwise the vector remains unchanged.

`initialize_from_string` is a good idea to combine both goals without breaking existing behaviour.

Yes, I'm using it in productive code and need to use VS2010...

**Comment by d-led** [comment]
@ihcaesar thanks! Do you have performance concerns, thus the request?

what about

```
        template < typename T>
        std::string initialize_from_string(std::string const& json, T& t) {
            t = T();
            return from_string(json, t);
        }
```
?

**Comment by ihcaesar** [comment]
Fine!

No performance concerns. I use the serialization for configuration objects that don't change much.

My problem occured while re-reading the configuration. I didn't expect this behaviour of deserialization: 
JSON contains [A, B, C], deserializing results in vector A, B, C. Deserializing same JSON to same object again results in vector A,B,C,A,B,C and so on ;-)

Perhaps others don't expect this behavoiur, too - so I wrote this request.

**Comment by d-led** [comment]
I see! Would you like to propose the change yourself, and add a test that verifies the behavior? I wouldn't be able to work on it today

**Comment by d-led** [comment]
@acidtonic this might solve the problem you solved with your fork too

**Comment by d-led** [comment]
@ihcaesar the problem should be solved now

**Comment by ihcaesar** [comment]
@d-led Thanks!
